In [3]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv("../dataset/apple_global_sales_dataset.csv")

df.head()

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,storage,color,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,previous_device_os,customer_rating,return_status
0,APPL-00000001,2022-01-03,2022,Q1,January,Argentina,South America,Buenos Aires,AirPods (3rd Gen),AirPods,NaN,Starlight,159.27,7,1,148.12,148.12,ARS,907.0,134344.84,Third-Party Retailer,Cash,Government,45–54,NaN,4.1,Kept
1,APPL-00000002,2022-01-04,2022,Q1,January,Argentina,South America,Buenos Aires,USB-C Woven Charge Cable,Accessories,NaN,Black,29.99,15,5,25.49,127.45,ARS,907.0,115597.15,Authorized Reseller,Debit Card,Business,45–54,NaN,4.8,Kept
2,APPL-00000003,2022-05-18,2022,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,NaN,Titanium,293.92,0,4,293.92,1175.68,ARS,907.0,1066341.76,Corporate / B2B,Credit Card,Individual,18–24,NaN,4.3,Kept
3,APPL-00000004,2022-05-23,2022,Q2,May,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,1 TB SSD,Starlight,1932.77,0,2,1932.77,3865.54,ARS,907.0,3506044.78,Carrier Store,Credit Card,Education,45–54,NaN,NaN,Kept
4,APPL-00000005,2022-07-13,2022,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,NaN,Midnight,755.44,5,3,717.67,2153.01,ARS,907.0,1952780.07,Apple Store,Net Banking,Education,18–24,NaN,NaN,Kept

In [5]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11500 entries, 0 to 11499
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sale_id                 11500 non-null  object
 1   sale_date               11500 non-null  object
 2   year                    11500 non-null  int64
 3   quarter                 11500 non-null  object
 4   month                   11500 non-null  object
 5   country                 11500 non-null  object
 6   region                  11500 non-null  object
 7   city                    11500 non-null  object
 8   product_name            11500 non-null  object
 9   category                11500 non-null  object
 10  storage                 6696 non-null   object
 11  color                   11500 non-null  object
 12  unit_price_usd          11500 non-null  float64
 13  discount_pct            11500 non-null  int64
 14  units_sold              11500 non-null  int64
 15  discounted_price_usd    11500 non-null  float64
 16  revenue_usd             11500 non-null  float64
 17  currency                11500 non-null  object
 18  fx_rate_to_usd          11500 non-null  float64
 19  revenue_local_currency  11500 non-null  float64
 20  sales_channel           11500 non-null  object
 21  payment_method          11500 non-null  object
 22  customer_segment        11500 non-null  object
 23  customer_age_group      11500 non-null  object
 24  previous_device_os      3444 non-null   object
 25  customer_rating         8140 non-null   float64
 26  return_status           11500 non-null  object
dtypes: float64(6), int64(3), object(18)
memory usage: 2.4+ MB

In [6]:
df.isnull().sum()

sale_id                      0
sale_date                    0
year                         0
quarter                      0
month                        0
country                      0
region                       0
city                         0
product_name                 0
category                     0
storage                   4804
color                        0
unit_price_usd               0
discount_pct                 0
units_sold                   0
discounted_price_usd         0
revenue_usd                  0
currency                     0
fx_rate_to_usd               0
revenue_local_currency       0
sales_channel                0
payment_method               0
customer_segment             0
customer_age_group           0
previous_device_os        8056
customer_rating           3360
return_status                0
dtype: int64

In [7]:
print("Jumlah duplikasi: ", df.duplicated().sum())

Jumlah duplikasi:  0

In [8]:
df.describe()

,year,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,fx_rate_to_usd,revenue_local_currency,customer_rating
count,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,1.150000e+04,8140.000000
mean,2022.997304,807.851191,3.841565,2.023478,777.365478,1568.319065,1029.406647,1.464369e+06,4.000934
std,0.821747,1112.437595,4.783161,1.443599,1072.915122,2839.759822,4072.334957,9.941160e+06,0.575192
min,2022.000000,26.690000,0.000000,1.000000,22.730000,23.000000,0.790000,2.130000e+01,3.000000
25%,2022.000000,180.147500,0.000000,1.000000,178.297500,305.740000,0.920000,1.041693e+03,3.500000
50%,2023.000000,593.905000,2.000000,1.000000,573.420000,833.040000,7.240000,6.164160e+03,4.000000
75%,2024.000000,958.387500,7.000000,3.000000,928.567500,1748.360000,91.500000,7.471653e+04,4.500000
max,2024.000000,7551.010000,15.000000,8.000000,7551.010000,59529.520000,24500.000000,5.075175e+08,5.000000

# Cleaning Dataset

In [9]:
# Mengganti NaN pada kolom storage
df['storage'] = df['storage'].fillna('Not Applicable')

# Cek hasilnya
df['storage'].isnull().sum()

np.int64(0)

In [10]:
# Menghapus kolom previous_device_os
df = df.drop(columns=['previous_device_os'])

# Cek apakah sudah terhapus
df.columns

Index(['sale_id', 'sale_date', 'year', 'quarter', 'month', 'country', 'region',
       'city', 'product_name', 'category', 'storage', 'color',
       'unit_price_usd', 'discount_pct', 'units_sold', 'discounted_price_usd',
       'revenue_usd', 'currency', 'fx_rate_to_usd', 'revenue_local_currency',
       'sales_channel', 'payment_method', 'customer_segment',
       'customer_age_group', 'customer_rating', 'return_status'],
      dtype='object')

In [11]:
df['customer_rating'] = df.groupby('category')['customer_rating'].transform(lambda x: x.fillna(x.median()))

In [12]:
df.head()

,sale_id,sale_date,year,quarter,month,country,region,city,product_name,category,storage,color,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,currency,fx_rate_to_usd,revenue_local_currency,sales_channel,payment_method,customer_segment,customer_age_group,customer_rating,return_status
0,APPL-00000001,2022-01-03,2022,Q1,January,Argentina,South America,Buenos Aires,AirPods (3rd Gen),AirPods,Not Applicable,Starlight,159.27,7,1,148.12,148.12,ARS,907.0,134344.84,Third-Party Retailer,Cash,Government,45–54,4.1,Kept
1,APPL-00000002,2022-01-04,2022,Q1,January,Argentina,South America,Buenos Aires,USB-C Woven Charge Cable,Accessories,Not Applicable,Black,29.99,15,5,25.49,127.45,ARS,907.0,115597.15,Authorized Reseller,Debit Card,Business,45–54,4.8,Kept
2,APPL-00000003,2022-05-18,2022,Q2,May,Argentina,South America,Buenos Aires,Apple Watch Series 8,Apple Watch,Not Applicable,Titanium,293.92,0,4,293.92,1175.68,ARS,907.0,1066341.76,Corporate / B2B,Credit Card,Individual,18–24,4.3,Kept
3,APPL-00000004,2022-05-23,2022,Q2,May,Argentina,South America,Buenos Aires,MacBook Pro 14-inch (M3),Mac,1 TB SSD,Starlight,1932.77,0,2,1932.77,3865.54,ARS,907.0,3506044.78,Carrier Store,Credit Card,Education,45–54,4.0,Kept
4,APPL-00000005,2022-07-13,2022,Q3,July,Argentina,South America,Buenos Aires,Apple Watch Ultra 2,Apple Watch,Not Applicable,Midnight,755.44,5,3,717.67,2153.01,ARS,907.0,1952780.07,Apple Store,Net Banking,Education,18–24,4.0,Kept

# EDA

In [13]:
df.describe()

,year,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,fx_rate_to_usd,revenue_local_currency,customer_rating
count,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,11500.000000,1.150000e+04,11500.000000
mean,2022.997304,807.851191,3.841565,2.023478,777.365478,1568.319065,1029.406647,1.464369e+06,4.000661
std,0.821747,1112.437595,4.783161,1.443599,1072.915122,2839.759822,4072.334957,9.941160e+06,0.483914
min,2022.000000,26.690000,0.000000,1.000000,22.730000,23.000000,0.790000,2.130000e+01,3.000000
25%,2022.000000,180.147500,0.000000,1.000000,178.297500,305.740000,0.920000,1.041693e+03,3.700000
50%,2023.000000,593.905000,2.000000,1.000000,573.420000,833.040000,7.240000,6.164160e+03,4.000000
75%,2024.000000,958.387500,7.000000,3.000000,928.567500,1748.360000,91.500000,7.471653e+04,4.300000
max,2024.000000,7551.010000,15.000000,8.000000,7551.010000,59529.520000,24500.000000,5.075175e+08,5.000000

In [14]:
# Ambil hanya kolom numerik
numeric_df = df.select_dtypes(include=['int64', 'float64'])

# Hitung korelasi
correlation_matrix = numeric_df.corr()

correlation_matrix

,year,unit_price_usd,discount_pct,units_sold,discounted_price_usd,revenue_usd,fx_rate_to_usd,revenue_local_currency,customer_rating
year,1.000000,0.017683,-0.014136,0.008704,0.017541,0.008819,0.003457,0.011903,-0.005310
unit_price_usd,0.017683,1.000000,-0.010308,-0.003446,0.998301,0.755070,-0.010482,0.133406,0.001451
discount_pct,-0.014136,-0.010308,1.000000,-0.005998,-0.044947,-0.038354,-0.014628,-0.021520,0.012346
units_sold,0.008704,-0.003446,-0.005998,1.000000,-0.003011,0.384497,0.002207,0.083551,0.000526
discounted_price_usd,0.017541,0.998301,-0.044947,-0.003011,1.000000,0.757582,-0.009426,0.135874,0.000466
revenue_usd,0.008819,0.755070,-0.038354,0.384497,0.757582,1.000000,-0.012978,0.139827,0.001143
fx_rate_to_usd,0.003457,-0.010482,-0.014628,0.002207,-0.009426,-0.012978,1.000000,0.583349,-0.003618
revenue_local_currency,0.011903,0.133406,-0.021520,0.083551,0.135874,0.139827,0.583349,1.000000,-0.002161
customer_rating,-0.005310,0.001451,0.012346,0.000526,0.000466,0.001143,-0.003618,-0.002161,1.000000

In [15]:
df.to_csv("apple_sales_cleaned.csv", index=False)